
name: Build and deploy API to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
        working-directory: ./server

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./server

      # Optional: Add step to run tests here

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        working-directory: ./server

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: quizwiz-api
          path: |
            server/release.zip
            !server/venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build


    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: quizwiz-api

      - name: Unzip artifact for deployment
        run: unzip release.zip


      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'quizwiz'
          slot-name: 'Production'
          publish-profile: ${{ secrets.__publishingprofilesecretname__ }}